mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('mysite.views',
	url(r'^$','hello'),
	url(r'^time/$','current_datetime'),
	url(r'^time/plus/(?P<offset>\d{1,2})$','hours_ahead'),
)
urlpatterns += patterns('mysite.books.views',
	url(r'^search/$','search'),
)
urlpatterns += patterns('mysite.contact.views',
    url(r'^contact/$','contact'),
    url(r'^contact/thanks/$','thanks'),
)

mysite/books/models.py
from django.db import models

class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()
	
	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ['name']
class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField(blank=True,verbose_name='e-mail')
	
	def __unicode__(self):
		return u'%s %s' % (self.first_name,self.last_name)

class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField()
	
	def __unicode__(self):
		return self.title

mysite/contact/forms.py
from django import forms
class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False,label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
					
#	def clean_message(self):
#        message = self.cleaned_data['message']
#        num_words = len(message.split())
#        if num_words < 4 :
#            raise forms.ValidationError('Not enough words!')
#		return message
				
				

mysite/books/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template,Context
from django.shortcuts import render_to_response
from mysite.books.models import Book
def display_meta(request):
	meta = request.META.items()
	meta.sort()
	return render_to_response('meta.html',locals()) 


def search(request):
	errors = []  
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			errors.append('Enter a search term.')
		elif len(q)>20:
			errors.append('Please enter at most 20 characters.')
		else:
			books = Book.objects.filter(title__icontains=q)	
			return render_to_response('search_results.html',{'books':books,'query':q})
	return render_to_response('search_form.html',{'errors':errors}) 
		

mysite/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
#from django.views.decorators.csrf import csrf_protect
#@csrf_protect
from mysite.contact.forms import ContactForm
#def contact(request):
#    errors = []
#    if request.method == 'POST':
#        if not request.POST.get('subject',''):
#            errors.append('Enter a subject.')
#        if not request.POST.get('message',''):
#            errors.append('Enter a message.')
#        if request.POST.get('email') and '@' not in request.POST['email']:
#            errors.append('Enter a valid e-mail address.')
#        if not errors:
#            send_mail(
#                request.POST['subject'],
#                request.POST['message'],
#                request.POST.get('email','noreplay@example.com'),
#                ['50406166@qq.com'],
#            )
#            return render_to_response('thanks.html',{'foo':'bad'},context_instance=RequestContext(request))
#    return render_to_response('contact_form.html',{'errors':errors},context_instance=RequestContext(request))


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(cd['subject'],cd['message'],cd.get('email','noreplay@example.com'),['50406166@qq.com'])
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(initial={'subject':'I love your site!'})
    return render_to_response('contact_form.html',{'form':form},context_instance=RequestContext(request))

def thanks(request):
    return render_to_response('thanks.html',{'foo':'bar'})

mysite/views.py
from django.template.loader import get_template
from django.template import Template,Context
from django.http import HttpResponse
import datetime
def hello(request):
	return HttpResponse('Hello world!')

def current_datetime(request):
	now = datetime.datetime.now()
	t = get_template('current_datetime.html')
	html = t.render(Context({'current_date':now}))
	return HttpResponse(html)

#Can be replace with the underline function
#from django.shortcuts import render_to_response
#def current_datetime(request):
#	current_date = datetime.datetime.now()
#	return render_to_response('current_datetime.html',locals())

from django.shortcuts import render_to_response
def hours_ahead(request,offset):
	try:
		hours_offset = int(offset)
		next_time = datetime.datetime.now() + datetime.timedelta(hours=hours_offset)
	except ValueError:
		raise Http404
	return render_to_response('hours_ahead.html',locals())

mysite/books/templates/meta.html
<html>
	<table>
	{% for k,v in meta %}
	<tr>
		<td>{{k}}</td>
		<td>{{v}}</td>	
	</tr>
	{% endfor %}	
	</table>
</html>

mysite/books/templates/search_form.html
<html>
	<head>
		<title>Search</title>
	</head>
	<body>
		{% if errors %}
		<ul>
			{% for error in errors %}
			<li style="color:red;">{{error}} </li>
			{% endfor %}
		</ul>
		{% endif %}
		<form action="" method="get">
			<table>
				<tr>
					<td><p>user</p></td>
					<td><input type="text" name="user"></td>
				</tr>	
				<tr>
					<td><p>bookname</p></td>
					<td><input type="text" name="q"></td>
				</tr>	
				<tr>
					<td><input type="submit" value="Search"></td>
				</tr>	
			</table>
		</form>
	</body>	
</html>

mysite/books/templates/search_results.html
<p>You searched for: <strong>{{query}}</strong></p>

{% if books %}
	<p>Found {{books|length}} book{{books|pluralize}}.</p>
	<ul>
		{% for book in books %}
		<li>{{book.title}}</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No books matched your search criteria.</p>
{% endif %}

mysite/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<h1>My helpful timestamp site</h1>
	{% block content %}{% endblock %}
	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

mysite/templates/contact_form.html
<html>
    <head>
		<style type="text/css">
			ul.errorlist {margin:0;padding:0;}
			.errorlist li {background-color:red;color:white;display:block;font-size:10px;margin: 0 0 3px;padding:4px 5px;}
		</style>
        <title>Contact us</title>
     </head>
     <body>
        <h1>Contact us</h1>
        {% if form.errors %}
            <p style="color:red;">
                Please correct the error{{form.errors|pluralize}} below.
            </p>
        {% endif %}
        <form action="" method="post">
        {% csrf_token %}
<!--        <table>
                {{form.as_table}}
            </table>-->
			<div class="field">
				{{form.subject.errors}}
				<label for="id_subject">Subject:</label>
				{{form.subject}}
			</div>
			<div class="field">
				{{form.email.errors}}
				<label for="id_email">Your e-mail address:</label>
				{{form.email}}
			</div>
			<div class="field">
				{{form.message.errors}}
				<label for="id_message">Message:</label>
				{{form.message}}
			</div>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>
			

mysite/templates/current_datetime.html
{% extends "base.html" %}
{% block title %}The current time {% endblock %}
{% block content %}
<p>It is now {{current_date}}.</p>
{% endblock %}

mysite/templates/hours_ahead.html
{% extends "base.html" %}
{% block title %}Future time{% endblock %}
{%block content %}
<p>In {{hours_offset}} hour(s),it will be {{next_time}}. </p>
{%endblock%}

mysite/templates/thanks.html
<html>
    <head>
        <title>Thanks</title>
    </head>
    <body>
        <p>Thanks for you response</p>
    </body>
</html>